In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
df=pd.read_csv('/content/data.csv')
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [63]:
df.shape

(4600, 18)

In [64]:
df=df.drop(['date','street','statezip'],axis=1)

In [65]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country'],
      dtype='object')

In [66]:
len(df['city'].unique())

44

In [67]:
f = {}
s = 0

for i in df['city']:
  if i not in f:
    f[i] = s
    s = s + 1
  else:
    pass
df['city'] = df['city'].map(f).astype(int)

In [68]:
df['city'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [69]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  city  \
0     0          3        1340              0      1955          2005     0   
1     4          5        3370            280      1921             0     1   
2     0          4        1930              0      1966             0     2   
3     0          4        1000           1000      1963             0     3   
4     0          4        1140            800      1976          1992     4   

  country  
0     USA  
1     USA  
2     USA  
3     USA  
4     USA

In [70]:
df['country'].unique()

array(['USA'], dtype=object)

In [71]:
len(df['country'].unique())

1

In [72]:
df['country']=df['country'].map({'USA':1}).astype(int)

In [87]:
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  city  \
0     0          3        1340              0      1955          2005     0   
1     4          5        3370            280      1921             0     1   
2     0          4        1930              0      1966             0     2   
3     0          4        1000           1000      1963             0     3   
4     0          4        1140            800      1976          1992     4   

   country  
0        1  
1        1  
2        1  
3        1  
4        1

In [74]:
df['country'].unique()

array([1])

In [75]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'country'],
      dtype='object')

In [76]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [77]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [78]:
from sklearn.linear_model import LinearRegression
m=LinearRegression()
m.fit(x_train,y_train)

LinearRegression()

In [79]:
m.coef_

array([-6.21434797e+04,  3.18388178e+04,  1.86594299e+02, -3.90510293e-01,
        5.82032101e+04,  4.08914899e+05,  4.59124048e+04,  3.18945285e+04,
        1.03227800e+02,  8.33664988e+01, -2.27063299e+03,  8.50100956e+00,
       -3.21491270e+03,  0.00000000e+00])

In [80]:
m.intercept_

np.float64(4362144.739654726)

In [81]:
ans_train=m.predict(x_train)

In [82]:
from sklearn.metrics import mean_squared_error, r2_score
print(f'mse {mean_squared_error(y_train,ans_train)}')
print(f'train acc {r2_score(y_train,ans_train)}')

mse 64019244169.593895
train acc 0.5494327981279497


In [83]:
ans_test=m.predict(x_test)
print(f'mse {mean_squared_error(y_test,ans_test)}')
print(f'test acc {r2_score(y_test,ans_test)}')

mse 984018336882.1514
test acc 0.03513078568458505


In [84]:
import pickle

In [85]:
with open('MLR_TEST.pkl','wb') as f:
  pickle.dump(m,f)

In [86]:
with open('/content/MLR_TEST.pkl','rb') as f:
  m=pickle.load(f)

OOPS CODE

In [95]:
class MLR:
  def __init__(self,d):
    self.df=pd.read_csv(d)
    self.df=self.df.drop(['date','street','statezip'],axis=1)
    f = {}
    s = 0
    for i in self.df['city']:
      if i not in f:
        f[i] = s
        s = s + 1
      else:
        pass
    self.df['city'] = self.df['city'].map(f).astype(int)
    self.df['country']=self.df['country'].map({'USA':1}).astype(int)
    self.x=self.df.iloc[:,1:]
    self.y=self.df.iloc[:,0]
    self.x_train,self.x_test,self.y_train,self.y_test=train_test_split(self.x,self.y,test_size=0.2,random_state=42)

  def train(self):
    self.m=LinearRegression()
    self.m.fit(self.x_train,self.y_train)
    self.ans_train=self.m.predict(self.x_train)
    print(f'mse {mean_squared_error(self.y_train,self.ans_train)}')
    print(f'train acc {r2_score(self.y_train,self.ans_train)}')
  def test(self):
    self.ans_test=self.m.predict(self.x_test)
    print(f'mse {mean_squared_error(self.y_test,self.ans_test)}')
    print(f'test acc {r2_score(self.y_test,self.ans_test)}')
if __name__=="__main__":
  obj=MLR('/content/data.csv')
  obj.train()
  obj.test()

mse 64019244169.593895
train acc 0.5494327981279497
mse 984018336882.1514
test acc 0.03513078568458505
